### ISSUE TITLE
MongoError: topology was destroyed

### ISSUE THREAD

**Issue by Vanuan** [datagovua/edrpou-api#7]
```
edr_1           | Sending 500 ("Server Error") response: 
edr_1           |  Error (E_UNKNOWN) :: Encountered an unexpected error
edr_1           | MongoError: topology was destroyed
edr_1           |     at Server.insert (/src/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:956:49)
edr_1           |     at Server.insert (/src/node_modules/sails-mongo/node_modules/mongodb/lib/server.js:325:17)
edr_1           |     at executeCommands (/src/node_modules/sails-mongo/node_modules/mongodb/lib/bulk/ordered.js:453:23)
edr_1           |     at OrderedBulkOperation.execute (/src/node_modules/sails-mongo/node_modules/mongodb/lib/bulk/ordered.js:506:10)
edr_1           |     at bulkWrite (/src/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:592:8)
edr_1           |     at Collection.insertMany (/src/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:483:44)
edr_1           |     at Collection.insert (/src/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:766:15)
edr_1           |     at Collection.insert (/src/node_modules/sails-mongo/lib/collection.js:185:48)
edr_1           |     at Object.module.exports.adapter.create (/src/node_modules/sails-mongo/lib/adapter.js:303:18)
edr_1           |     at module.exports.create (/src/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:84:13)
edr_1           |     at createValues (/src/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:220:16)
edr_1           |     at /src/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:74:20
edr_1           |     at /src/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:726:13
edr_1           |     at /src/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:52:16
edr_1           |     at /src/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:269:32
edr_1           |     at /src/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:44:16
edr_1           | 

```

**Comment by Vanuan** [comment]
got rid of mongo
